name: Auto update

on:
  schedule:
    - cron: '15 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'current'
      - run: git config --global user.name "auto-update" && git config --global user.email "auto-update@example.com"
      - run: npm ci
      - run: npm run update
